services:
  - type: web
    name: silverfox-moon-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python manage.py migrate --noinput
      gunicorn backend.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: silverfox-moon-backend.onrender.com
      - key: OPENAI_API_KEY
        sync: false
