# Generated by Django 5.2 on 2025-04-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoonMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('phase', models.CharField(max_length=50)),
                ('sign', models.CharField(max_length=50)),
                ('emoji', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('emotion_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
